Repository stripe/stripe-go, pull requests merged in 2018-08, with the labels that each got.

#646 Set request body before every retry
  stripe.go
  stripe_test.go
Labels: approved

#658 Remove the form package's `zero` option
  form/form.go
  form/form_test.go
Labels: approved

#663 Add support for usage record summary
  .travis.yml
  issuerfraudrecord.go
  sourcetransaction.go
  testing/testing.go
  usagerecord.go
  usagerecord_test.go
  usagerecordsummary.go
  usagerecordsummary/client.go
  usagerecordsummary/client_test.go
Labels: breaking-api-change

#668 Move to API version 2018-08-23
  .travis.yml
  customer.go
  plan.go
  plan/client_test.go
  plan_test.go
  stripe.go
  sub.go
  sub/client_test.go
  testing/testing.go
Labels: breaking-api-change

#673 Remove racy test in favor of simpler one
  stripe_test.go
Labels: approved

#674 Fix payment intent parameters
  paymentintent.go
  paymentintent/client.go
Labels: breaking-api-change

#676 Remove `TestBankAccountGet_ByAccount` test
  bankaccount/client_test.go
Labels: approved

#677 Remove the right test
  bankaccount/client_test.go
Labels: approved

#678 Fix subscription item listing test
  subitem/client_test.go
Labels: approved

#680 SubscriptionTaxPercent should be a float64, not int64
  invoice.go
Labels: approved, breaking-api-change
