Repository stripe/stripe-go, pull requests merged in 2018-06, with the labels that each got.

#579 format the example README code
  README.md
Labels: approved

#583 Add new constants, rename one and fix DueBy
  account.go
  account/client_test.go
  account_test.go
Labels: breaking-api-change

#585 Remove File in favor of FileUpload
  dispute.go
  fileupload.go
  fileupload_test.go
Labels: approved, breaking-api-change

#587 Use `net/http` constants instead of string literals for HTTP verbs
  account/client.go
  applepaydomain/client.go
  balance/client.go
  bankaccount/client.go
  bitcoinreceiver/client.go
  bitcointransaction/client.go
  card/client.go
  charge/client.go
  countryspec/client.go
  coupon/client.go
  customer/client.go
  discount/client.go
  dispute/client.go
  ephemeralkey/client.go
  error_test.go
  event/client.go
  exchangerate/client.go
  fee/client.go
  feerefund/client.go
  fileupload/client.go
  invoice/client.go
  invoiceitem/client.go
  issuerfraudrecord/client.go
  loginlink/client.go
  order/client.go
  orderreturn/client.go
  paymentsource/client.go
  payout/client.go
  plan/client.go
  product/client.go
  recipient/client.go
  refund/client.go
  reversal/client.go
  sku/client.go
  source/client.go
  sourcetransaction/client.go
  stripe.go
  sub/client.go
  subitem/client.go
  threedsecure/client.go
  token/client.go
  topup/client.go
  transfer/client.go
  usagerecord/client.go
Labels: approved

#589 Fix all Get methods to support Params and remove deprecated ones
  charge/client.go
  charge/client_test.go
  countryspec.go
  countryspec/client.go
  countryspec/client_test.go
  event.go
  event/client.go
  exchangerate.go
  exchangerate/client.go
  exchangerate/client_test.go
  issuerfraudrecord.go
  issuerfraudrecord/client.go
  issuerfraudrecord/client_test.go
  loginlink.go
  loginlink/client.go
Labels: breaking-api-change

#591 Organize core files alphabetically and into sections
  iter.go
  params.go
  stripe.go
Labels: approved

#593 Activate linting for a few packages
  .travis.yml
  Makefile
  account/client.go
  charge/client.go
Labels: approved

#599 Adds missing ExchangeRate field to BalanceTransaction
  balance.go
Labels: approved

#605 Use `travis_retry` helper when using `go get` for dependencies
  .travis.yml
Labels: approved

#609 Add some "app info" tests for `X-Stripe-Client-User-Agent`
  stripe_test.go
Labels: approved
