Repository stripe/stripe-go, pull requests merged in 2019-02, with the labels that each got.

#787 Add support for `transfer_data[amount]` on Charge
  charge.go
Labels: approved

#737 Add support for capabilities on the `Account` resource
  account.go
  account_test.go
Labels: approved

#793 Add support for save_payment_method on PaymentIntent
  paymentintent.go
Labels: approved

#782 Add support for API version 2019-02-19
  .travis.yml
  account.go
  account/client_test.go
  account_test.go
  countryspec.go
  paymentintent.go
  person.go
  person/client_test.go
  testing/testing.go
Labels: breaking-api-change

#794 Fix API version which should be pinned to 2019-02-19 instead
  stripe.go
Labels: approved, breaking-api-change

#796 Make invoice items a slice, as per API spec
  invoice.go
Labels: approved

#800 Add usagerecordsummary to the list of clients
  client/api.go
Labels: approved

#795 Add support for `created` and `status_transitions` on `Invoice`
  invoice.go
Labels: approved

#802 Add support for `latest_invoice` on `Subscription`
  sub.go
Labels: approved

#803 Add support for `api_version` on `WebhookEndpoint` and fix a test.
  webhookendpoint.go
Labels: approved
