Repository stripe/stripe-go, pull requests merged in 2019-03, with the labels that each got.

#798 Prevents `Object` from being serialized on the `Event` resource
  event.go
Labels: approved

#805 Add README section on configurable retries
  README.md
Labels: approved

#807 Add `current_period_*` filters when listing Invoices
  sub.go
Labels: approved

#808 Add new fields to Subscription
  sub.go
Labels: approved

#810 Add support for columns on Reporting resources
  reporting_reportrun.go
  reporting_reporttype.go
Labels: approved

#806 Add support for PaymentMethod
  .travis.yml
  charge.go
  error.go
  paymentintent.go
  paymentmethod.go
  paymentmethod/client.go
  paymentmethod/client_test.go
  testing/testing.go
  token/client_test.go
Labels: approved

#812 Add support for Terminal Location and Reader deletion
  terminal/location/client.go
  terminal/location/client_test.go
  terminal/reader/client.go
  terminal/reader/client_test.go
  terminal_location.go
  terminal_reader.go
Labels: approved

#811 Add support for API version 2019-03-14
  .travis.yml
  charge.go
  ephemeralkey/client_test.go
  invoice.go
  stripe.go
  sub.go
Labels: approved

#814 Properly override API version if it's set in the request
  stripe.go
Labels: breaking-api-change

#815 Add support for passing an Account Token on Account or Person creation
  account.go
  person.go
Labels: approved

#819 Add log prefixes + test suite
  log.go
  log_test.go
Labels: approved

#820 Add a long list of missing params and properties
  charge.go
  customer.go
  invoice.go
  invoiceitem.go
  issuerfraudrecord.go
  issuing_authorization.go
  issuing_card.go
  issuing_cardholder.go
  issuing_dispute.go
  issuing_transaction.go
  loginlink.go
  order.go
  paymentintent.go
  payout.go
  plan.go
  product.go
  refund.go
  reversal.go
  sub.go
  subschedule.go
  token.go
  token/client_test.go
  topup.go
  transfer.go
Labels: approved, breaking-api-change

#821 Add non-null params for capture in test
  charge/client_test.go
  paymentintent/client_test.go
Labels: approved
